# Generated by Django 3.1.7 on 2021-04-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210410_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lead',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
