# Generated by Django 3.1.7 on 2021-04-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210410_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='https://picsum.photos/100/100/?random=1', upload_to='static/img/upload/'),
        ),
    ]
