# Generated by Django 3.1.7 on 2021-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='https://picsum.photos/300/200/?random=1', max_length=300, upload_to='img/upload/'),
        ),
    ]
