# Generated by Django 3.1.7 on 2021-04-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210410_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://picsum.photos/300/200/?random=1', max_length=300, null=True, upload_to='img/'),
        ),
    ]
