# Generated by Django 3.1.7 on 2021-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210412_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/lus-200.jpg', null=True, upload_to=''),
        ),
    ]
