# Generated by Django 3.1.7 on 2021-04-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210412_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lead',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
