# Generated by Django 3.1.7 on 2021-04-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20210415_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='new_price',
            field=models.FloatField(default=1, max_length=15),
        ),
    ]
