# Generated by Django 3.1.7 on 2021-04-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20210415_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='new_price',
            new_name='real_price',
        ),
    ]
