# Generated by Django 3.1.7 on 2021-04-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20210415_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='real_price',
        ),
    ]
