# Generated by Django 3.1.7 on 2021-04-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_remove_crypto_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='real_price',
            field=models.FloatField(max_length=15, null=True),
        ),
    ]
