# Generated by Django 3.1.7 on 2021-04-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_crypto_real_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='price',
        ),
        migrations.AddField(
            model_name='crypto',
            name='real_price',
            field=models.FloatField(null=True),
        ),
    ]
