# Generated by Django 3.1.7 on 2021-04-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_crypto_real_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='real_price',
            field=models.JSONField(verbose_name='get_crypto.json_data'),
        ),
    ]
