# Generated by Django 3.1.7 on 2021-04-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_remove_crypto_real_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crypto',
        ),
    ]
