# Generated by Django 3.2.3 on 2021-06-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20210503_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
